# Generated by Django 2.2.3 on 2019-07-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('testproject', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='ForeignModelWithoutUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignModelWithUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='category',
            field=models.CharField(
                choices=[('blog_post', 'Blog Post'), ('foo', 'Foo'), ('bar', 'Bar')], max_length=128
            ),
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='foreign_1',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testproject.ForeignModelWithUrl'
            ),
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='foreign_2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='testproject.ForeignModelWithoutUrl',
            ),
        ),
    ]
