# Generated by Django 2.2.16 on 2020-10-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0002_auto_20190728_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='some_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='some_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
